In [82]:
# imports the necessary python modules 
import pandas as pd
import requests
import wikipedia as wp
from bs4 import BeautifulSoup
import numpy as np

In [106]:
# reads in airport data
airport_data = pd.read_table("/Users/nialdaly/Documents/CSC7052_Data_Preprocessing/raw_data/airports.dat", sep=",", header=None)

# assigns column headings
airport_data.columns = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 13]

# selects specific columns pandas
airport_data = airport_data[['1','2', '3', '4', '5', '6', '7', '8','9']]

# renames the headers
airport_data.columns = ['AirportName', 'City', 'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', '8', '9']

airport_data.head()

,AirportName,City,Country,IATA,ICAO,Latitude,Longitude,8,9
0,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10
1,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10
2,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10
3,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10
4,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10

In [107]:
# uses wikipedia module to obtain easyjet aiports
easyjet_airports = wp.page("List of EasyJet destinations").html().encode("UTF-8")
easyjet_airports = pd.read_html(html)[1]

# makes first row the header row
easyjet_airports.columns = easyjet_airports.iloc[0]
easyjet_airports = easyjet_airports.reindex(easyjet_airports.index.drop(0))

# drop notes column
easyjet_airports = easyjet_airports.drop('Notes', 1)

easyjet_airports.head()

0        City   Country IATA  ICAO                       Airport
1  Klagenfurt   Austria  KLU  LOWK            Klagenfurt Airport
2    Salzburg   Austria  SZG  LOWS              Salzburg Airport
3      Vienna   Austria  VIE  LOWW  Vienna International Airport
4    Brussels   Belgium  BRU  EBBR              Brussels Airport
5       Sofia  Bulgaria  SOF  LBSF                 Sofia Airport

In [108]:
# extracts all base airports
easyjet_airports_base = easyjet_airports[easyjet_airports['Airport'].str.contains("Base")]

# resets and drops the index
easyjet_airports_base = easyjet_airports_base.reset_index(drop=True)
#
easyjet_airports_base.head()

0      City Country IATA  ICAO                               Airport
0  Bordeaux  France  BOD  LFBD    BordeauxâMÃ©rignac Airport[Base]
1      Lyon  France  LYS  LFLL  LyonâSaint-ExupÃ©ry Airport [Base]
2      Nice  France  NCE  LFMN      Nice CÃ´te d'Azur Airport [Base]
3     Paris  France  CDG  LFPG      Charles de Gaulle Airport [Base]
4     Paris  France  ORY  LFPO                   Orly Airport [Base]

In [109]:
#
easyjet_airports_base = pd.merge(easyjet_airports_base, airport_data, on='IATA', how='left')
easyjet_airports_base.head()

,City_x,Country_x,IATA,ICAO_x,Airport,AirportName,City_y,Country_y,ICAO_y,Latitude,Longitude,8,9
0,Bordeaux,France,BOD,LFBD,BordeauxâMÃ©rignac Airport[Base],Bordeaux-Mérignac Airport,Bordeaux,France,LFBD,44.828300,-0.715556,162.0,1
1,Lyon,France,LYS,LFLL,LyonâSaint-ExupÃ©ry Airport [Base],Lyon Saint-Exupéry Airport,Lyon,France,LFLL,45.725556,5.081111,821.0,1
2,Nice,France,NCE,LFMN,Nice CÃ´te d'Azur Airport [Base],Nice-Côte d'Azur Airport,Nice,France,LFMN,43.658401,7.215870,12.0,1
3,Paris,France,CDG,LFPG,Charles de Gaulle Airport [Base],Charles de Gaulle International Airport,Paris,France,LFPG,49.012798,2.550000,392.0,1
4,Paris,France,ORY,LFPO,Orly Airport [Base],Paris-Orly Airport,Paris,France,LFPO,48.723333,2.379444,291.0,1

In [115]:
# selects specific columns pandas
easyjet_airports_base = easyjet_airports_base[['AirportName','City_y', 'Country_y', 'IATA', 'Latitude', 'Longitude']]

# drops any rows containing NaNs
easyjet_airports_base = easyjet_airports_base.dropna()

# renames the headers
easyjet_airports_base.columns = ['AirportName', 'City', 'Country', 'AirportCode', 'Latitude', 'Longitude']

easyjet_airports_base.head()

,AirportName,City,Country,AirportCode,Latitude,Longitude
0,Bordeaux-Mérignac Airport,Bordeaux,France,BOD,44.828300,-0.715556
1,Lyon Saint-Exupéry Airport,Lyon,France,LYS,45.725556,5.081111
2,Nice-Côte d'Azur Airport,Nice,France,NCE,43.658401,7.215870
3,Charles de Gaulle International Airport,Paris,France,CDG,49.012798,2.550000
4,Paris-Orly Airport,Paris,France,ORY,48.723333,2.379444

In [116]:
# outputs the data to csv
easyjet_airports_base.to_csv("/Users/nialdaly/Documents/CSC7052_Data_Preprocessing/data/airports.csv", index=False)